AWSTemplateFormatVersion: "2010-09-09"
Description: Deploy Helm into an EKS cluster
Parameters:
  EKSCAData:
    Type: String
  EKSEndpoint:
    Type: String
  EKSArn:
    Type: String
  TillerInstallLambdaArn:
    Type: String
  KubeManifestLambdaArn:
    Type: String
Resources:
  TillerInstall:
    DependsOn: TillerRoleBinding
    Type: "Custom::TillerInstall"
    Version: '1.0'
    Properties:
      ServiceToken: !Ref TillerInstallLambdaArn
      EKSCAData: !Ref EKSCAData
      EKSEndpoint: !Ref EKSEndpoint
      EKSArn: !Ref EKSArn
      TillerSA: tiller
  TillerSA:
    Type: "Custom::KubeManifest"
    Version: '1.0'
    Properties:
      ServiceToken: !Ref KubeManifestLambdaArn
      EKSCAData: !Ref EKSCAData
      EKSEndpoint: !Ref EKSEndpoint
      EKSArn: !Ref EKSArn
      Manifest:
        apiVersion: v1
        kind: ServiceAccount
        metadata:
          name: tiller
          namespace: kube-system
  TillerRoleBinding:
    DependsOn: TillerSA
    Type: "Custom::KubeManifest"
    Version: '1.0'
    Properties:
      ServiceToken: !Ref KubeManifestLambdaArn
      EKSCAData: !Ref EKSCAData
      EKSEndpoint: !Ref EKSEndpoint
      EKSArn: !Ref EKSArn
      Manifest:
        apiVersion: rbac.authorization.k8s.io/v1beta1
        kind: ClusterRoleBinding
        metadata:
          name: tiller
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: ClusterRole
          name: cluster-admin
        subjects:
        - kind: ServiceAccount
          name: tiller
          namespace: kube-system
